version: "3"
services:

  frontend:
    build: 
      context: ./src/frontend/
      dockerfile: develop.Dockerfile
    image: frontend
    volumes:
      - ./src/frontend:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    